gallery-email-parse: Fix compatibilty with new requests
The `config` option was removed in requests 1.0+

Fixes exception in sending to galleri email of form:
    TypeError: request() got an unexpected keyword argument 'config'